name: CI/CD Pipeline Microservicios
on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # ==========================================
    # DESPLIEGUE DE VENTAS
    # ==========================================
    - name: Construir y subir imagen de VENTAS
      working-directory: ./Springboot-API-REST-VENTA
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ev2/back-ventas
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
    - name: Codificar docker-compose a Base64
      run: echo "COMPOSE_VENTAS_B64=$(base64 -w 0 ./Springboot-API-REST-VENTA/docker-compose.yml)" >> $GITHUB_ENV

    - name: Actualizar contenedor VENTAS 
      run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.INSTANCE_ID_VENTAS }} \
            --document-name "AWS-RunShellScript" \
            --comment "Desplegar Ventas " \
            --parameters '{"commands":[
              "set -e",
              
              "mkdir -p /home/ec2-user/app-ventas",
              "cd /home/ec2-user/app-ventas",
              
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
              
              "echo \"${{ env.COMPOSE_VENTAS_B64 }}\" | base64 -d > docker-compose.yml",
              
              "export IMAGE_URL=${{ steps.login-ecr.outputs.registry }}/ev2/back-ventas:latest",
              
              "docker pull $IMAGE_URL",
              
              "docker-compose down || true",
              "docker-compose up -d"
            ]}' \
            --output text

    # ==========================================
    # DESPLIEGUE DE DESPACHO
    # ==========================================
    - name: Construir y subir imagen de DESPACHO
      working-directory: ./Springboot-API-REST-DESPACHO
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ev2/back-despacho
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Codificar docker-compose Despacho a Base64
      run: echo "COMPOSE_DESPACHO_B64=$(base64 -w 0 ./Springboot-API-REST-DESPACHO/docker-compose.yml)" >> $GITHUB_ENV

    - name: Actualizar contenedor DESPACHO
      run: |
        aws ssm send-command \
            --instance-ids ${{ secrets.INSTANCE_ID_DESPACHO }} \
            --document-name "AWS-RunShellScript" \
            --comment "Desplegar Despacho" \
            --parameters '{"commands":[
              "set -e",
              
              "mkdir -p /home/ec2-user/app-despacho",
              "cd /home/ec2-user/app-despacho",
              
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
              
              "echo \"${{ env.COMPOSE_DESPACHO_B64 }}\" | base64 -d > docker-compose.yml",
              
              "export IMAGE_URL=${{ steps.login-ecr.outputs.registry }}/ev2/back-despacho:latest",
              
              "docker pull $IMAGE_URL",
              
              "docker-compose down || true",
              "docker-compose up -d"
            ]}' \
            --output text
